// apps/svelte/src/lib/Board.svelte
<script lang="ts">
  import * as core from 'core';

  export let rows: number;
  export let cols: number;
  export let mode: string = 'edit';
  export let steps: number = 0;

  let board: core.Board;
  let mousedown = false;

  export const reset = () => {
    board = core.generateNewBoard(rows, cols);
  };

  const next = () => {
    board = core.getNextBoard(board);
  };

  const handleCellClick = (row: number, col: number) => {
    if (mode === 'edit') {
      board[row][col] = board[row][col] ? 0 : 1;
    }
  };

  $: rows && cols && reset();

  $: steps && next();
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
  class="board"
  on:mousedown={() => (mousedown = true)}
  on:mouseup={() => (mousedown = false)}
>
  {#if board}
    {#each board as row, i}
      <div class="row">
        {#each row as cell, j}
          <div
            class="cell"
            class:edit={mode === 'edit'}
            style="background-color: {cell ? 'black' : 'white'};"
            on:mouseenter={() => {
              if (mousedown) {
                handleCellClick(i, j);
              }
            }}
            on:click={() => handleCellClick(i, j)}
          />
        {/each}
      </div>
    {/each}
  {/if}
</div>

<style>
  .board {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .row {
    display: flex;
  }

  .cell {
    min-width: 14px;
    min-height: 14px;
    width: 14x;
    height: 14px;
    background-color: white;
    border: 1px solid black;
  }

  .cell.edit {
    cursor: pointer;
  }
</style>

// apps/react/src/lib/Board.tsx
/* eslint-disable react-hooks/exhaustive-deps */
import {
  useCallback,
  useEffect,
  useState,
  forwardRef,
  useImperativeHandle,
} from 'react';
import * as core from 'core';
import './Board.css';

export type BoardProps = {
  rows: number;
  cols: number;
  mode: string;
  steps: number;
};

export type BoardRef = {
  reset: () => void;
};

const Board = forwardRef<BoardRef, BoardProps>((props, ref) => {
  const [board, setBoard] = useState<core.Board>([]);
  //   const [mousedown, setMousedown] = useState(false);

  const handleCellClick = useCallback(
    (row: number, col: number) => {
      const newBoard = [...board];
      newBoard[row][col] =
        newBoard[row][col] === core.CellStatus.Live
          ? core.CellStatus.Dead
          : core.CellStatus.Live;
      setBoard(newBoard);
    },
    [board]
  );

  const reset = useCallback(() => {
    const newBoard = core.generateNewBoard(props.rows, props.cols);
    setBoard(newBoard);
  }, [props.rows, props.cols]);

  useImperativeHandle(ref, () => ({
    reset: () => reset(),
  }));

  useEffect(() => {
    reset();
  }, [props.rows, props.cols]);

  useEffect(() => {
    const newBoard = core.getNextBoard(board);
    setBoard(newBoard);
  }, [props.steps]);

  useEffect(() => {
    reset();
  }, []);

  return (
    <div
      className="board"
      //   on:mousedown={() => (mousedown = true)}
      //   on:mouseup={() => (mousedown = false)}
    >
      {board.map((row, rowIndex) => (
        <div className="row" key={rowIndex}>
          {row.map((cell, colIndex) => (
            <div
              className={`cell`}
              style={{
                backgroundColor:
                  cell === core.CellStatus.Live ? 'black' : 'white',
              }}
              key={colIndex}
              onClick={() => handleCellClick(rowIndex, colIndex)}
            ></div>
          ))}
        </div>
      ))}
    </div>
  );
});

export default Board;
